-- Run this once in Supabase Dashboard > SQL Editor.
-- Create users with Authentication > Users, not in this SQL file.

create table if not exists public.login_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  email text not null,
  role text not null check (role in ('family', 'doctor')),
  created_at timestamptz default now() not null
);

create table if not exists public.hydration_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  glasses integer not null check (glasses between 0 and 8),
  created_at timestamptz default now() not null
);

create table if not exists public.medication_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  medication_name text not null,
  taken boolean not null,
  created_at timestamptz default now() not null
);

create table if not exists public.game_scores (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  game_name text not null,
  moves integer not null check (moves >= 0),
  time_seconds integer not null check (time_seconds >= 0),
  score numeric not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz default now() not null
);

alter table public.game_scores add column if not exists metadata jsonb not null default '{}'::jsonb;

alter table public.login_history enable row level security;
alter table public.hydration_logs enable row level security;
alter table public.medication_logs enable row level security;
alter table public.game_scores enable row level security;

drop policy if exists "Users can insert their own login history" on public.login_history;
drop policy if exists "Users can view their own login history" on public.login_history;
drop policy if exists "Users can insert their own hydration logs" on public.hydration_logs;
drop policy if exists "Users can view their own hydration logs" on public.hydration_logs;
drop policy if exists "Users can insert their own medication logs" on public.medication_logs;
drop policy if exists "Users can view their own medication logs" on public.medication_logs;
drop policy if exists "Users can insert their own game scores" on public.game_scores;
drop policy if exists "Users can view their own game scores" on public.game_scores;

create policy "Users can insert their own login history"
  on public.login_history for insert with check (auth.uid() = user_id);
create policy "Users can view their own login history"
  on public.login_history for select using (auth.uid() = user_id);

create policy "Users can insert their own hydration logs"
  on public.hydration_logs for insert with check (auth.uid() = user_id);
create policy "Users can view their own hydration logs"
  on public.hydration_logs for select using (auth.uid() = user_id);

create policy "Users can insert their own medication logs"
  on public.medication_logs for insert with check (auth.uid() = user_id);
create policy "Users can view their own medication logs"
  on public.medication_logs for select using (auth.uid() = user_id);

create policy "Users can insert their own game scores"
  on public.game_scores for insert with check (auth.uid() = user_id);
create policy "Users can view their own game scores"
  on public.game_scores for select using (auth.uid() = user_id);
